name: 'app-windows'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build-tauri:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Write mah build config
        shell: powershell
        run: |
          $data = @{ name = 'Mah'; mobile = true }
          $data | ConvertTo-Json | Set-Content -Path custom-build-config.json


      - name: Install mah dependencies
        run: npm install

      - name: Install tauri dependencies
        run: cd resources/apps && npm install

      - name: Build windows app
        run: |
          cd resources/apps
          npm run windows


      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        if: github.ref_type != 'tag'
        with:
          name: 'windows'
          retention-days: 10
          path: resources/apps/tauri/target/x86_64-pc-windows-msvc/release/bundle/

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            resources/apps/tauri/target/x86_64-pc-windows-msvc/release/bundle/**/*.msi
            resources/apps/tauri/target/x86_64-pc-windows-msvc/release/bundle/**/*.exe

